# Generated by Django 5.0.4 on 2024-05-08 05:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=tinymce.models.HTMLField(),
        ),
    ]
